// scripts/embed-presets.mjs
//
// 构建期把 sidepanel/userscripts/ 下的用户脚本源码「硬编码」进 bundle：
// 生成 background/preset-sources.generated.ts，导出 PRESET_SOURCES（文件名→源码字符串）。
//
// 用途：dev 构建（__DEV__=true）的预装机制直接读本地硬编码源码，彻底跳过 jsDelivr @dev
// 分支缓存（最长约 12h），改完脚本 → build → reload 即生效，零推送零 CDN 等待。
// 正式发布（__DEV__=false）仍走 CDN（按版本 tag 拉取，保留「打 tag 即更新预装」能力）。
//
// 该文件由 build / dev / typecheck / test 脚本前置调用；生成的 .ts 进 .gitignore。
import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const srcDir = resolve(root, 'sidepanel/userscripts');
const outFile = resolve(root, 'background/preset-sources.generated.ts');

const sources = {};
if (existsSync(srcDir)) {
  // 严格按预装白名单 presets.json 内联：清单本身 + 其登记的全部脚本
  // （pet-chat.js 是 .js、非 .user.js，也必须进 bundle，故以清单为准而非后缀过滤）
  const manifestRaw = readFileSync(resolve(srcDir, 'presets.json'), 'utf-8');
  let manifest = [];
  try { manifest = JSON.parse(manifestRaw); } catch { /* 清单损坏则只内联清单本身 */ }
  sources['presets.json'] = manifestRaw;
  for (const f of manifest) {
    const p = resolve(srcDir, f);
    if (existsSync(p)) sources[f] = readFileSync(p, 'utf-8');
  }
}

const content =
  '// AUTO-GENERATED by scripts/embed-presets.mjs — do not edit.\n' +
  '// Regenerated on every build. Inlined user-script sources for dev (local) preset install.\n' +
  `export const PRESET_SOURCES: Record<string, string> = ${JSON.stringify(sources, null, 2)};\n`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, content);
console.log(`  ✓ embedded ${Object.keys(sources).length} preset source(s) → background/preset-sources.generated.ts`);
